name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Build project
        run: ./mvnw clean package -DskipTests=false

      - name: Run tests
        run: ./mvnw test

      - name: Log in to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t arthursidor/treecount-api:latest .

      - name: Push Docker image
        run: docker push arthursidor/treecount-api:latest

      # Exemplo simples de deploy
      - name: Deploy (Staging)
        run: |
          docker pull arthursidor/treecount-api:latest
          docker stop treecount-api || true
          docker rm treecount-api || true
          docker run -d -p 8080:8080 --name treecount-api arthursidor/treecount-api:latest
