name: CI/CD

on:
  push:
    branches:
      - master    # Staging
  workflow_dispatch:   # Permite rodar manualmente (para produção)

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Tornar mvnw executável
        run: chmod +x ./mvnw

      - name: Build project
        run: ./mvnw clean package

      - name: Run tests
        run: ./mvnw test

      - name: Log in to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t arthursidor/treecount-api:latest .

      - name: Push Docker image
        run: docker push arthursidor/treecount-api:latest

  deploy-staging:
    needs: build-test-docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            docker pull arthursidor/treecount-api:latest
            docker stop treecount-api || true
            docker rm treecount-api || true
            docker run -d -p 8080:8080 --name treecount-api arthursidor/treecount-api:latest

  deploy-production:
    if: github.event_name == 'workflow_dispatch'  # Só roda manualmente
    needs: build-test-docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            docker pull arthursidor/treecount-api:latest
            docker stop treecount-api || true
            docker rm treecount-api || true
            docker run -d -p 8080:8080 --name treecount-api arthursidor/treecount-api:latest
